.TH DISK_STAT 1 
.SH NAME
disk_stat \- Show the details of a disk - LINUX ONLY
.SH SYNOPSIS
.B disk_stat [-V]
.I hd_device

.SH DESCRIPTION
.B disk_stat
works in only Linux and uses ATA commands to query a harddisk.  The
important information that it currently gives is the actual number
of sectors and if there is a Host Protected Area (HPA) on the disk.  

.SH ARGUMENTS
.IP -V
Display version
.IP hd_device
The device corresponding to the hard disk.  Typically it is /dev/hdX.


.SH "EXAMPLES"

disk_stat /dev/hdd

.SH HISTORY
.BR "disk_stat" " first appeared in " "The Sleuth Kit" " v1.73."

It is based on code from http://www.win.tue.nl/~aeb/linux/setmax.c

.SH LIMITATIONS
disk_stat works only in Linux and does not support large disks.  It will
also not work on ATA disks connected with USB or Firewire.

.SH AUTHOR
Brian Carrier <carrier at sleuthkit dot org>

Send documentation updates to <doc-updates at sleuthkit dot org>
