.TH DISK_SRESET 1 
.SH NAME
disk_sreset \- Temporarily reset the size of an ATA disk - LINUX ONLY
.SH SYNOPSIS
.B disk_sreset [-V]
.I hd_device

.SH DESCRIPTION
.B disk_sreset
works in only Linux and uses ATA commands to query a harddisk.  If 
there is a Host Protected Area, then it temporarily removes it so
that the full disk can be acquired.  When the disk is powered off or
reset, then the HPA will exist again.

.SH ARGUMENTS
.IP -V
Display version
.IP hd_device
The device corresponding to the hard disk.  Typically it is /dev/hdX.


.SH "EXAMPLES"

disk_sreset /dev/hdd

.SH HISTORY
.BR "disk_sreset" " first appeared in " "The Sleuth Kit" " v2.00."

It is based on code from http://www.win.tue.nl/~aeb/linux/setmax.c

.SH LIMITATIONS
disk_sreset works only in Linux and does not support large disks.  It will
also not work on ATA disks connected with USB or Firewire.

.SH AUTHOR
Brian Carrier <carrier at sleuthkit dot org>

Send documentation updates to <doc-updates at sleuthkit dot org>
