language: "en-US"
tone_instructions: ""
early_access: false
enable_free_tier: true

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "develop"
      - "develop-4.14"

chat:
  auto_reply: true
