#!/bin/sh
autoreconf --force --install || aclocal --force -I m4 \
    && (libtoolize -c --force || glibtoolize -c --force) \
    && autoheader --force \
    && autoconf --force \
    && automake --foreign --add-missing --copy
