# validate this with:
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate

coverage:
  range: 40..60
  round: nearest
  precision: 2

codecov:
  branch: develop

ignore:
  - "m4"
  - "test"
  - "vendors"

# Code for updating pull request comment on GitHub
# See https://docs.codecov.com/docs/pull-request-comments
comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false     # post comment even if no required change
  require_base: false        # [true :: must have a base report to post]
  require_head: false        # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff]
