name: 'Build And Test'
description: 'Performs a build and test on The Sleuth Kit'

runs: 
  using: "composite"
  steps:
    - name: Install Dependencies
      run: |
        sudo apt update &&
        sudo apt -y install build-essential autoconf libtool automake git zip wget ant \
        libpq-dev \
        testdisk libafflib-dev libewf-dev libvhdi-dev libvmdk-dev && \
    - name: Fix Line Endings
      run: |
        sudo apt update &&
        sudo apt -y install dos2unix &&
        find . \( -name "*.m4" -o -name "*.ac" -o -name "*.am" \) | xargs dos2unix
    - name: Build And Install
      run: |
        chmod a+x ./bootstrap && 
        ./bootstrap && 
        chmod a+x ./configure && 
        ./configure &&
        make &&
        sudo make install
    - name: Run The Sleuth Kit tests
      run: ant -f ./bindings/java clean dist test