#!/usr/bin/env python3
"""Emit unit_tests/base/xpress_test_data.h from the xpress fixture vectors."""
import sys

sys.path.insert(0, r'C:\Users\ADMIN\AppData\Local\Temp\opencode\ghost-recover\tests')
import xpress_fixture as xf

out = []
out.append('/* Generated by tests/xpress fixture encoder; do not edit. */')
out.append('#ifndef XPRESS_TEST_DATA_H')
out.append('#define XPRESS_TEST_DATA_H')
out.append('')
out.append('#include <stddef.h>')
out.append('')

plains = [
    b'GHOST//RECOVER data recovery engine.\n',
    b'abc' * 100,
    b'P' * 40,
    b'A' * 700,
    b'Q' * 4000,
    b'abcdefghij' * 30,
    b'abcdefghij' * 3 + b'!' + b'abcdefghij' * 3,
    bytes((i * 7 + 3) % 251 for i in range(9000)),
]
huffs = [
    b'The quick brown fox jumps over the lazy dog. ' * 8,
    b'abcdabcdabcdabcd' * 600,
    b'z' * 3000,
    bytes(((i * 13 + 5) % 253) for i in range(20000)),
    b'x' * 65536,
    b'x' * 21,
    b'abcdefghijklmnopqrst' * 2,
]

vectors = []  # (name, enc_bytes, plain_len, huff_flag)


def emit(name, enc, plain, huff):
    vectors.append((name, enc, len(enc), plain, huff))
    out.append('static const unsigned char %s[] = {' % name)
    row = []
    for i, c in enumerate(enc):
        row.append('0x%02x' % c)
        if len(row) == 12:
            out.append('    ' + ', '.join(row) + ',')
            row = []
    if row:
        out.append('    ' + ', '.join(row) + ',')
    out.append('};')
    out.append('')


for i, d in enumerate(plains):
    name = 'kXpPlain%d' % i
    emit(name, xf.PlainLz77Encoder(d).encode(), len(d), 0)
for i, d in enumerate(huffs):
    name = 'kXpHuff%d' % i
    emit(name, xf.HuffmanEncoder(d).encode(), len(d), 1)
emit('kXpAnchor', xf.anchor_block(), 300, 1)

out.append('static const struct XpressTestVector {')
out.append('    const unsigned char *data;')
out.append('    size_t coded;')
out.append('    size_t plain;')
out.append('    int huff;')
out.append('} kXpressVectors[] = {')
for name, enc, coded, plain, huff in vectors:
    out.append('    { %s, %d, %d, %d },' % (name, coded, plain, huff))
out.append('};')
out.append('')
out.append('#endif /* XPRESS_TEST_DATA_H */')

path = r'C:\Users\ADMIN\AppData\Local\Temp\opencode\tsk-clone\unit_tests\base\xpress_test_data.h'
open(path, 'w').write('\n'.join(out))
print('wrote %s with %d vectors' % (path, len(vectors)))