name: "Build"

# For docker container comparable to Linux build worker:
#   docker run -it docker.io/library/ubuntu:22.04 bash

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:  # Manual trigger for testing

jobs:
  build:
    timeout-minutes: 30
    name: posix ${{matrix.prefix}} ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.linkage }} ${{ matrix.compiler }} ${{ matrix.suffix }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "macos"
            arch: "arm64"
            linkage: "shared"
            compiler: "gcc"
            runner: "macos-15"
            configure_opts: "--with-libewf --enable-java"
            make_flags: "CFLAGS=-Werror CXXFLAGS=-Werror"
            codecov: "yes"
            prefix: "CODECOV"
            address_sanitizer: "yes"
            keep_artifacts: "no"
            enable_java: "yes"

          - os: "linux"
            arch: "x86_64"
            linkage: "shared"
            compiler: "gcc"
            runner: "ubuntu-24.04"
            configure_opts: "--with-libewf --with-libqcow --with-libvhdi --with-libvmdk --enable-java"
            make_flags: "CFLAGS=-Werror CXXFLAGS=-Werror"
            codecov: "no"
            prefix:
            address_sanitizer: "yes"
            keep_artifacts: "yes"
            suffix: "(with artifacts)"
            enable_java: "yes"

          - os: "linux"
            arch: "x86_64"
            linkage: "shared"
            compiler: "clang"
            runner: "ubuntu-24.04"
            configure_opts: "--with-libewf --with-libqcow --with-libvhdi --with-libvmdk --enable-java CC=clang CXX=clang++"
            make_flags: "CFLAGS=-Werror CXXFLAGS=-Werror"
            codecov: "no"
            prefix: ""
            address_sanitizer: "yes"
            keep_artifacts: "no"
            enable_java: "yes"

          - os: "mingw"
            arch: "x86_64"
            linkage: "shared"
            compiler: "gcc"
            runner: "ubuntu-24.04"
            configure_opts: "--host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --disable-java --enable-shared --disable-static"
            winearch: 'win64'
            winepath: 'Z:\usr\lib\gcc\x86_64-w64-mingw32\13-posix'
            wineprefix: '/home/runner/.wine64'
            codecov: "no"
            prefix: ""
            address_sanitizer: "no"
            keep_artifacts: "no"

          - os: "mingw"
            arch: "x86_64"
            linkage: "static"
            compiler: "gcc"
            runner: "ubuntu-24.04"
            configure_opts: "--host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --disable-java --disable-shared --enable-static"
            winearch: 'win64'
            winepath: 'Z:\usr\lib\gcc\x86_64-w64-mingw32\13-posix'
            wineprefix: '/home/runner/.wine64'
            codecov: "no"
            prefix: ""
            address_sanitizer: "no"
            keep_artifacts: "no"

          - os: "mingw"
            arch: "i686"
            linkage: "shared"
            compiler: "gcc"
            runner: "ubuntu-24.04"
            configure_opts:   "--host=i686-w64-mingw32 --target=i686-w64-mingw32 --enable-shared --disable-static --disable-java"
            configure_optsnj: "--host=i686-w64-mingw32 --target=i686-w64-mingw32 --enable-shared --disable-static"
            winearch: 'win32'
            winepath: 'Z:\usr\lib\gcc\i686-w64-mingw32\13-posix'
            wineprefix: '/home/runner/.wine32'
            codecov: "no"
            prefix: ""
            address_sanitizer: "no"
            keep_artifacts: "no"

          - os: "mingw"
            arch: "i686"
            linkage: "static"
            runner: "ubuntu-24.04"
            compiler: "gcc"
            configure_opts:   "--host=i686-w64-mingw32 --target=i686-w64-mingw32 --disable-shared --enable-static --disable-java"
            configure_optsnj: "--host=i686-w64-mingw32 --target=i686-w64-mingw32 --disable-shared --enable-static"
            winearch: 'win32'
            winepath: 'Z:\usr\lib\gcc\i686-w64-mingw32\13-posix'
            wineprefix: '/home/runner/.wine32'
            codecov: "no"
            prefix: ""
            address_sanitizer: "no"
            keep_artifacts: "no"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: ${{ matrix.os == 'mingw' && 1 || 0 }}

      - uses: ./.github/actions/builder
