name: TSK Tests on Windows

on:
  push:
    branches:
      - '**' # This will trigger the action for all branches
  pull_request:
    branches:  # Specify the branches for which pull_request events should trigger the action
      - main
      - develop

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x86, x64]
    runs-on: windows-latest

    env:
      TSK_HOME: "${{ github.workspace }}"

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
      - uses: microsoft/setup-msbuild@v1.1

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco install nuget.commandline
          choco install ant --ignore-dependencies

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # choose 'temurin', 'zulu' or 'adopt'
          java-version: '17'

      - name: Print the Java release from JAVA_HOME
        shell: bash
        run: |
          find $JAVA_HOME -print

      - name: Set JDK_HOME and INCLUDE
        shell: bash
        run: |
          echo "JDK_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "INCLUDE=$INCLUDE;$JAVA_HOME/include;$JAVA_HOME/include/win32" >> $GITHUB_ENV

      - name: Demo JAVA_HOME/include/jni.h
        shell: bash
        run: |
          ls -l $JAVA_HOME/include/jni.h
          echo INCLUDE=$INCLUDE
          ls -l $GITHUB_ENV

      - name: bash printenv
        shell: bash
        run: |
          printenv | sort

      - name: Build TSK
        run: |
          python win32\updateAndBuildAll.py -m

      - name: Build Java
        run: |
          ant -version
          cd bindings\java
          ant -q dist
          cd ..\..
          cd case-uco\java
          ant -q
          cd ..\..

      - name: List all files
        shell: bash
        run: |
          find . -ls
