name: The Sleuth Kit Tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  

jobs:
  java8build:    
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/bellsoft-java8-full-amd64
    steps:
    - uses: actions/checkout@v3
    - name: Install Java 8
      run: |
        # technique taken from https://stackoverflow.com/a/71384057/2375948
        wget -O- https://download.bell-sw.com/pki/GPG-KEY-bellsoft | gpg --dearmor | sudo tee /usr/share/keyrings/bellsoft.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/bellsoft.gpg] https://apt.bell-sw.com/ stable main" |\
        sudo tee /etc/apt/sources.list.d/bellsoft.list && \
        sudo apt update && \
        sudo apt -y install bellsoft-java8-full
    - name: Install Dependencies
      run: |
        sudo apt update &&
        sudo apt -y install build-essential autoconf libtool automake git zip wget ant \
        libpq-dev \
        testdisk libafflib-dev libewf-dev libvhdi-dev libvmdk-dev
    - name: Fix Line Endings
      run: |
        sudo apt update &&
        sudo apt -y install dos2unix &&
        find . \( -name "*.m4" -o -name "*.ac" -o -name "*.am" \) | xargs dos2unix
    - name: Build And Install
      run: |
        chmod a+x ./bootstrap && 
        ./bootstrap && 
        chmod a+x ./configure && 
        ./configure &&
        make &&
        sudo make install
    - name: Run The Sleuth Kit tests
      run: ant -f ./bindings/java clean dist test

  java17build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Java 17
      run: |
        sudo apt update &&
        sudo apt -y install openjdk-17-jdk openjdk-17-jre 
    - name: Install Dependencies
      run: |
        sudo apt update &&
        sudo apt -y install build-essential autoconf libtool automake git zip wget ant \
        libpq-dev \
        testdisk libafflib-dev libewf-dev libvhdi-dev libvmdk-dev
    - name: Fix Line Endings
      run: |
        sudo apt update &&
        sudo apt -y install dos2unix &&
        find . \( -name "*.m4" -o -name "*.ac" -o -name "*.am" \) | xargs dos2unix
    - name: Build And Install
      run: |
        chmod a+x ./bootstrap && 
        ./bootstrap && 
        chmod a+x ./configure && 
        ./configure &&
        make &&
        sudo make install
    - name: Run The Sleuth Kit tests
      run: ant -f ./bindings/java clean dist test