name: Sleuthkit Tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  

jobs:
  java8build:    
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/bellsoft-java8-full-amd64
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt update &&
        sudo apt -y install build-essential autoconf libtool automake git zip wget ant \
        libpq-dev \
        testdisk libafflib-dev libewf-dev libvhdi-dev libvmdk-dev && \
        pushd /usr/src/ && 
        wget -q -O - https://download.bell-sw.com/pki/GPG-KEY-bellsoft | sudo apt-key add - &&
        echo "deb [arch=amd64] https://apt.bell-sw.com/ stable main" | sudo tee /etc/apt/sources.list.d/bellsoft.list &&
        sudo apt update &&
        sudo apt -y install bellsoft-java8-full &&
        echo "/usr/lib/jvm/bellsoft-java8-full-amd64/bin" >> $GITHUB_PATH
        popd
    - name: Fix Line Endings
      run: |
        sudo apt update &&
        sudo apt -y install dos2unix &&
        find . \( -name "*.m4" -o -name "*.ac" -o -name "*.am" \) | xargs dos2unix
    - name: Configure
      run: |
        chmod a+x ./bootstrap && 
        ./bootstrap && 
        chmod a+x ./configure && 
        ./configure
    - name: Make
      run: make 
    - name: Install
      run: sudo make install
    - name: Run The Sleuth Kit tests
      run: ant -f ./bindings/java clean dist test

  java17build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt update &&
        sudo apt -y install openjdk-17-jdk openjdk-17-jre \
        build-essential autoconf libtool automake git zip wget ant \
        libpq-dev \
        testdisk libafflib-dev libewf-dev libvhdi-dev libvmdk-dev 
    - name: Fix Line Endings
      run: |
        sudo apt update &&
        sudo apt -y install dos2unix &&
        find . \( -name "*.m4" -o -name "*.ac" -o -name "*.am" \) | xargs dos2unix
    - name: Configure
      run: |
        chmod a+x ./bootstrap && 
        ./bootstrap && 
        chmod a+x ./configure && 
        ./configure
    - name: Make
      run: make 
    - name: Install
      run: sudo make install
    - name: Run The Sleuth Kit tests
      run: ant -f ./bindings/java clean dist test